2021/11/19 00:00:27 [error] 285#285: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "localhost:81", referrer: "http://localhost:81/nginx/proxy"
